name: Deploy to Azure

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: dgwordgames-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: deploy

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login to Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: 'Create .env'
      run: |
        touch .env
        echo 'DG_PROJECT_ID=${{ secrets.DG_PROJECT_ID }}' >> .env
        echo 'DG_KEY=${{ secrets.DG_KEY }}' >> .env

    - name: 'Build Web'
      run: |
        npm install
        npm run build --if-present

    - uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}

    - name: Azure logout
      run: |
        az logout
      if: always()
